import { DEFAULT_PROTOCOL_PROFILES, type ProtocolIntent, type ProtocolKind } from "./protocols";
export interface RouteCandidate { readonly routeId:string; readonly capabilityId:string; readonly protocol:ProtocolKind; readonly providerId:string; readonly capabilityFit:number; readonly authoritySatisfied:boolean; readonly privacyScore:number; readonly availability:number; readonly trustScore:number; readonly valueScore:number; readonly latencyScore:number; readonly costScore:number; readonly dataBoundaryScore:number; readonly jurisdictionScore:number; readonly safe:boolean; readonly metadata?:Readonly<Record<string,unknown>>; }
export interface RouteContext { readonly intent:ProtocolIntent; readonly requiredCapabilityId:string; readonly authorityRequired?:boolean; readonly privateData?:boolean; readonly jurisdiction?:string; readonly maxCost?:number; readonly maxLatencyMs?:number; }
export interface RouteDecision { readonly selected?:RouteCandidate; readonly ranked:readonly RouteCandidate[]; readonly outcome:"selected"|"no-safe-route"; readonly reasons:readonly string[]; }
const PREF:Readonly<Record<ProtocolIntent,ProtocolKind>>={deterministic:"CLI","structured-tool-data":"MCP","agent-delegation":"A2A","direct-service":"API","embedded-performance":"SDK","browser-external-world":"WEB","private-edge":"LOCAL"};
const clamp=(n:number)=>Number.isFinite(n)?Math.max(0,Math.min(1,n)):0;
function score(c:RouteCandidate,p:ProtocolKind):number{return clamp(c.capabilityFit)*.22+(c.authoritySatisfied?.12:0)+clamp(c.privacyScore)*.1+clamp(c.availability)*.1+clamp(c.trustScore)*.18+clamp(c.valueScore)*.08+clamp(c.latencyScore)*.06+clamp(c.costScore)*.04+clamp(c.dataBoundaryScore)*.05+clamp(c.jurisdictionScore)*.05+(c.protocol===p?0.1:0);}
export function rankIntegrationRoutes(context:RouteContext,candidates:readonly RouteCandidate[]):RouteDecision{const preferred=PREF[context.intent]; const safe=candidates.filter(c=>c.safe&&c.capabilityId===context.requiredCapabilityId&&(!context.authorityRequired||c.authoritySatisfied)&&(!context.privateData||c.privacyScore>=.7)); const ranked=[...safe].sort((a,b)=>score(b,preferred)-score(a,preferred)); if(!ranked.length)return{ranked:[],outcome:"no-safe-route",reasons:["no candidate satisfies capability, safety, and authority constraints"]}; return{selected:ranked[0],ranked,outcome:"selected",reasons:[`preferred protocol for ${context.intent} is ${preferred}`,"provider popularity is not a constitutional authority signal"]};}
export function supportsProtocolIntent(protocol:ProtocolKind,intent:ProtocolIntent):boolean{return DEFAULT_PROTOCOL_PROFILES.find(p=>p.kind===protocol)?.supports.includes(intent)??false;}
