import assert from "node:assert/strict";
import test from "node:test";
import { AuthorityRuntime, AuthorityRecord } from "../src/authority-runtime";
import { EventStore } from "../src/event-runtime";
import { MemoryPersistenceAdapter } from "../src/persistence";

const issuer = (): AuthorityRecord => ({
  id: "governance-1", subject: "human-governance", issuer: "constitution",
  scope: ["authority:issue", "authority:delegate", "authority:revoke", "authority:suspend", "execute"],
  capabilities: ["authority:issue", "authority:delegate", "authority:revoke", "authority:suspend", "execute"],
  constraints: { resourceIds: ["resource-1"] }, context: { tenant: "tenant-1" },
  issued_at: new Date().toISOString(), expires_at: new Date(Date.now() + 3600000).toISOString(), revocable: true,
  provenance: { governance: true }, version: "1", status: "active"
});

async function runtime() { const persistence = new MemoryPersistenceAdapter(); return { persistence, events: new EventStore(persistence), runtime: new AuthorityRuntime({ persistence }) }; }

test("issues a valid scoped authority", async () => { const { runtime } = await runtime(); const created = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"], constraints: { resourceIds: ["resource-1"] }, context: { tenant: "tenant-1" }, idempotency_key: "issue-1" }, issuer()); assert.equal(created.status, "active"); assert.equal(created.version, "1"); assert.equal(created.issuer, "human-governance"); });
test("rejects issuance outside issuer scope", async () => { const { runtime } = await runtime(); await assert.rejects(() => runtime.issue({ subject: "human-1", scope: ["delete"], capabilities: ["delete"] }, issuer()), /exceeds issuer authority/); });
test("enforces resource and context constraints", async () => { const { runtime } = await runtime(); const a = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"], constraints: { resourceIds: ["resource-1"] }, context: { tenant: "tenant-1" } }, issuer()); await assert.rejects(() => runtime.authorizeAction(a.id, "execute", { resourceId: "resource-2", context: { tenant: "tenant-1" } })); await assert.rejects(() => runtime.authorizeAction(a.id, "execute", { resourceId: "resource-1", context: { tenant: "tenant-2" } })); });
test("capability mismatch is rejected", async () => { const { runtime } = await runtime(); const a = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"] }, issuer()); await assert.rejects(() => runtime.authorizeAction(a.id, "delete")); });
test("expired authority is rejected", async () => { const { runtime } = await runtime(); const a = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"], expires_at: new Date(Date.now() - 1000).toISOString() }, { ...issuer(), expires_at: new Date(Date.now() + 3600000).toISOString() }); await assert.rejects(() => runtime.authorizeAction(a.id, "execute"), /expired/); });
test("revoked authority is rejected", async () => { const { runtime } = await runtime(); const a = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"] }, issuer()); await runtime.revoke(a.id, issuer()); await assert.rejects(() => runtime.authorizeAction(a.id, "execute"), /revoked/); });
test("delegation is bounded by parent scope, capability, resource, context and duration", async () => { const { runtime } = await runtime(); const parent = await runtime.issue({ subject: "human-delegator", scope: ["authority:delegate", "execute"], capabilities: ["authority:delegate", "execute"], constraints: { resourceIds: ["resource-1"] }, context: { tenant: "tenant-1" }, expires_at: new Date(Date.now() + 1800000).toISOString() }, issuer()); const child = await runtime.delegate(parent.id, { subject: "agent-1", scope: ["execute"], capabilities: ["execute"], constraints: { resourceIds: ["resource-1"] }, context: { tenant: "tenant-1" }, expires_at: new Date(Date.now() + 1200000).toISOString() }, parent); assert.equal(child.parent_authority_id, undefined); assert.equal((child.provenance as Record<string, unknown>).parent_authority_id, parent.id); await assert.rejects(() => runtime.delegate(parent.id, { subject: "agent-2", scope: ["delete"], capabilities: ["delete"] }, parent), /exceeds parent authority/); });
test("ABBA cannot issue or delegate authority", async () => { const { runtime } = await runtime(); const abba = { ...issuer(), id: "abba", subject: "ABBA" }; await assert.rejects(() => runtime.issue({ subject: "agent-1", scope: ["execute"], capabilities: ["execute"] }, abba), /cannot issue/); await assert.rejects(() => runtime.delegate(abba.id, { subject: "agent-1", scope: ["execute"], capabilities: ["execute"] }, abba), /not found/); });
test("agent authority cannot issue or delegate", async () => { const { runtime } = await runtime(); const agent = { ...issuer(), id: "agent-auth", subject: "agent-1", provenance: { agent_id: "agent-1" } }; await assert.rejects(() => runtime.issue({ subject: "agent-2", scope: ["execute"], capabilities: ["execute"] }, agent), /non-agent governance/); });
test("issuance is idempotent", async () => { const { runtime } = await runtime(); const first = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"], idempotency_key: "same" }, issuer()); const second = await runtime.issue({ subject: "human-2", scope: ["execute"], capabilities: ["execute"], idempotency_key: "same" }, issuer()); assert.equal(first.id, second.id); });
test("revocation is version protected and idempotent after state is revoked", async () => { const { runtime } = await runtime(); const a = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"] }, issuer()); const revoked = await runtime.revoke(a.id, issuer(), "1"); assert.equal(revoked.status, "revoked"); await assert.rejects(() => runtime.revoke(a.id, issuer(), "1"), /version conflict|revoked/); });
test("audit events are generated for consequential authority decisions", async () => { const { runtime, events } = await runtime(); const a = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"] }, issuer()); await runtime.authorizeAction(a.id, "execute"); await runtime.revoke(a.id, issuer()); const types = (await events.all()).map((e) => e.type); assert.ok(types.includes("AUTHORITY_ISSUED")); assert.ok(types.includes("AUTHORITY_AUTHORIZATION")); assert.ok(types.includes("AUTHORITY_REVOKED")); });
test("authority survives runtime recreation through persistence", async () => { const persistence = new MemoryPersistenceAdapter(); const first = new AuthorityRuntime({ persistence }); const a = await first.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"] }, issuer()); const second = new AuthorityRuntime({ persistence }); assert.equal((await second.inspect(a.id))?.subject, "human-1"); });
test("stale authority mutation is rejected", async () => { const { runtime } = await runtime(); const a = await runtime.issue({ subject: "human-1", scope: ["execute"], capabilities: ["execute"] }, issuer()); const first = await runtime.suspend(a.id, issuer(), "1"); assert.equal(first.version, "2"); await assert.rejects(() => runtime.suspend(a.id, issuer(), "1"), /version conflict/); });
