export function createIOTransition({
  action,
  actorRef = null,
  principalRef = null,
  subjectRef = null,
  purpose = null,
  context = {},
  inputRefs = [],
  outputRefs = [],
  pulseRef = null,
  feedbackRef = null,
  valueRef = null,
  mintRef = null,
  representationRef = null,
  rightsRefs = [],
  provenanceRefs = [],
  evidenceRefs = [],
  ledgerRef = null,
  settlementRef = null,
  policyRef = null,
  previousState = null,
  resultingState = null,
  temporalValidity = null,
  metadata = {},
} = {}) {
  if (!action) throw new Error('action is required');
  return {
    id: `io-transition:${crypto.randomUUID()}`,
    kind: 'io-transition',
    action,
    actorRef,
    principalRef,
    subjectRef,
    purpose,
    context: { ...context },
    inputRefs: Array.isArray(inputRefs) ? [...inputRefs] : [],
    outputRefs: Array.isArray(outputRefs) ? [...outputRefs] : [],
    pulseRef,
    feedbackRef,
    valueRef,
    mintRef,
    representationRef,
    rightsRefs: Array.isArray(rightsRefs) ? [...rightsRefs] : [],
    provenanceRefs: Array.isArray(provenanceRefs) ? [...provenanceRefs] : [],
    evidenceRefs: Array.isArray(evidenceRefs) ? [...evidenceRefs] : [],
    ledgerRef,
    settlementRef,
    policyRef,
    previousState,
    resultingState,
    temporalValidity,
    status: 'pending',
    metadata: { ...metadata },
  };
}
