import { randomUUID } from "node:crypto";
import { authorize, EventStore } from "./event-runtime";
import { PersistencePort, MemoryPersistenceAdapter } from "./persistence";
import { Authority, JsonObject } from "./types";
export interface AuthorityIssueRequest { id?: string; subject: string; scope: string[]; capabilities: string[]; constraints?: JsonObject; context?: JsonObject; issued_at?: string; expires_at?: string; revocable?: boolean; provenance?: JsonObject; idempotency_key?: string; }
export interface AuthorityDecisionContext { resourceId?: string; context?: JsonObject; now?: Date; }
export interface AuthorityRecord extends Authority { version: string; status: "active" | "suspended" | "revoked" | "expired"; parent_authority_id?: string; context?: JsonObject; idempotency_key?: string; }
export interface AuthorityRuntimeOptions { persistence?: PersistencePort; events?: EventStore; abbaIdentity?: string; }
const ISSUE = "authority:issue"; const DELEGATE = "authority:delegate"; const REVOKE = "authority:revoke"; const SUSPEND = "authority:suspend"; const WILDCARD = "*";
function includesBounded(parent: string[], child: string[]): boolean { return child.every((value) => parent.includes(value) || parent.includes(WILDCARD)); }
function resourcesBounded(parent: AuthorityRecord, child: AuthorityIssueRequest): boolean { const p = Array.isArray(parent.constraints?.["resourceIds"]) ? parent.constraints["resourceIds"] as unknown[] : []; const c = Array.isArray(child.constraints?.["resourceIds"]) ? child.constraints["resourceIds"] as unknown[] : []; if (p.length === 0 || p.includes(WILDCARD)) return true; return c.every((value) => p.includes(value)); }
function contextBounded(parent: AuthorityRecord, child: AuthorityIssueRequest): boolean { const p = parent.context ?? {}; const c = child.context ?? {}; return Object.entries(p).every(([key, value]) => c[key] === value); }
function durationBounded(parent: AuthorityRecord, childExpiresAt?: string): boolean { if (!parent.expires_at) return true; if (!childExpiresAt) return false; return new Date(childExpiresAt).getTime() <= new Date(parent.expires_at).getTime(); }
function isExpired(authority: AuthorityRecord, now: Date): boolean { return !!authority.expires_at && new Date(authority.expires_at).getTime() <= now.getTime(); }
export class AuthorityRuntime {
  private readonly persistence: PersistencePort; private readonly events: EventStore; private readonly abbaIdentity: string;
  constructor(options: AuthorityRuntimeOptions = {}) { this.persistence = options.persistence ?? new MemoryPersistenceAdapter(); this.events = options.events ?? new EventStore(this.persistence); this.abbaIdentity = options.abbaIdentity ?? "ABBA"; }
  async issue(request: AuthorityIssueRequest, issuerAuthority: AuthorityRecord): Promise<AuthorityRecord> {
    if (!issuerAuthority.subject || issuerAuthority.subject === this.abbaIdentity || issuerAuthority.provenance?.["agent_id"]) throw new Error("Only non-agent governance authority may issue authority");
    authorize(issuerAuthority, ISSUE); if (!request.subject) throw new Error("Authority subject is required"); if (!request.scope.length || !request.capabilities.length) throw new Error("Authority scope and capabilities are required");
    if (!includesBounded(issuerAuthority.scope, request.scope)) throw new Error("Issued scope exceeds issuer authority"); if (!includesBounded(issuerAuthority.capabilities, request.capabilities)) throw new Error("Issued capabilities exceed issuer authority"); if (!resourcesBounded(issuerAuthority, request)) throw new Error("Issued resource scope exceeds issuer authority"); if (!contextBounded(issuerAuthority, request)) throw new Error("Issued context exceeds issuer authority"); if (!durationBounded(issuerAuthority, request.expires_at)) throw new Error("Issued duration exceeds issuer authority");
    const authority: AuthorityRecord = { id: request.id ?? randomUUID(), subject: request.subject, issuer: issuerAuthority.subject, scope: [...request.scope], capabilities: [...request.capabilities], constraints: structuredClone(request.constraints ?? {}), issued_at: request.issued_at ?? new Date().toISOString(), expires_at: request.expires_at, revocable: request.revocable ?? true, provenance: structuredClone(request.provenance ?? {}), version: "1", status: "active", parent_authority_id: typeof request.provenance?.["parent_authority_id"] === "string" ? request.provenance["parent_authority_id"] as string : undefined, context: structuredClone(request.context ?? {}), idempotency_key: request.idempotency_key };
    authority.provenance = { ...(authority.provenance ?? {}), issuer_authority_id: issuerAuthority.id };
    const created = structuredClone(await this.persistence.authorityIssue(authority as unknown as Record<string, unknown>) as unknown as AuthorityRecord);
    await this.events.append({ type: "AUTHORITY_ISSUED", actor: issuerAuthority.subject, subject: created.subject, outcome: "issued", provenance: { authority_id: created.id, issuer_authority_id: issuerAuthority.id }, payload: { scope: created.scope, capabilities: created.capabilities }, idempotency_key: `authority:issue:${created.id}` }); return created;
  }
  async inspect(id: string): Promise<AuthorityRecord | undefined> { const record = await this.persistence.read("authorities", id); return record ? structuredClone(record as unknown as AuthorityRecord) : undefined; }
  async validate(id: string, decision: AuthorityDecisionContext = {}): Promise<AuthorityRecord> { const authority = await this.require(id); const now = decision.now ?? new Date(); if (authority.status === "revoked" || authority.revoked_at) throw new Error("Authority has been revoked"); if (authority.status === "suspended") throw new Error("Authority has been suspended"); if (isExpired(authority, now)) { if (authority.status !== "expired") await this.markExpired(authority); throw new Error("Authority has expired"); } if (decision.resourceId && !this.resourceAllowed(authority, decision.resourceId)) throw new Error("Authority resource scope does not permit: " + decision.resourceId); if (decision.context && !this.contextAllowed(authority, decision.context)) throw new Error("Authority context is not permitted"); return authority; }
  async authorizeAction(id: string, capability: string, decision: AuthorityDecisionContext = {}): Promise<AuthorityRecord> { const authority = await this.validate(id, decision); authorize(authority, capability, decision.now ?? new Date()); await this.events.append({ type: "AUTHORITY_AUTHORIZATION", actor: authority.subject, subject: authority.subject, outcome: "authorized", provenance: { authority_id: authority.id }, payload: { capability, resourceId: decision.resourceId ?? null, context: decision.context ?? {} }, idempotency_key: `authority:authorize:${authority.id}:${capability}:${decision.resourceId ?? "*"}` }); return authority; }
  async delegate(parentId: string, request: AuthorityIssueRequest, delegator: AuthorityRecord): Promise<AuthorityRecord> { const parent = await this.validate(parentId); if (delegator.id !== parent.id || delegator.subject !== parent.subject) throw new Error("Delegator must possess the parent authority"); if (delegator.subject === this.abbaIdentity || delegator.provenance?.["agent_id"]) throw new Error("ABBA or an agent cannot delegate authority"); authorize(delegator, DELEGATE); if (!includesBounded(parent.scope, request.scope)) throw new Error("Delegated scope exceeds parent authority"); if (!includesBounded(parent.capabilities, request.capabilities)) throw new Error("Delegated capabilities exceed parent authority"); if (!resourcesBounded(parent, request)) throw new Error("Delegated resource scope exceeds parent authority"); if (!contextBounded(parent, request)) throw new Error("Delegated context exceeds parent authority"); if (!durationBounded(parent, request.expires_at)) throw new Error("Delegated duration exceeds parent authority"); const delegated = await this.issue({ ...request, provenance: { ...(request.provenance ?? {}), parent_authority_id: parent.id } }, delegator); await this.events.append({ type: "AUTHORITY_DELEGATED", actor: delegator.subject, subject: delegated.subject, outcome: "delegated", provenance: { authority_id: delegated.id, parent_authority_id: parent.id }, payload: { scope: delegated.scope, capabilities: delegated.capabilities }, idempotency_key: `authority:delegate:${delegated.id}` }); return delegated; }
  async revoke(id: string, actor: AuthorityRecord, expectedVersion?: string): Promise<AuthorityRecord> { const authority = await this.require(id); const expected = expectedVersion ?? authority.version; if (authority.version !== expected) throw new Error(`Authority version conflict: expected ${expected}, found ${authority.version}`); if (actor.subject === this.abbaIdentity || actor.provenance?.["agent_id"]) throw new Error("ABBA or an agent cannot revoke authority"); authorize(actor, REVOKE); if (!authority.revocable) throw new Error("Authority is not revocable"); if (authority.revoked_at) return authority; const revoked = structuredClone(await this.persistence.authorityRevoke({ id, expectedVersion: authority.version, revoked_at: new Date().toISOString() }) as unknown as AuthorityRecord); await this.events.append({ type: "AUTHORITY_REVOKED", actor: actor.subject, subject: authority.subject, outcome: "revoked", provenance: { authority_id: authority.id }, payload: { previous_version: authority.version }, idempotency_key: `authority:revoke:${authority.id}:${authority.version}` }); return revoked; }
  async suspend(id: string, actor: AuthorityRecord, expectedVersion?: string): Promise<AuthorityRecord> { const authority = await this.require(id); const expected = expectedVersion ?? authority.version; if (authority.version !== expected) throw new Error(`Authority version conflict: expected ${expected}, found ${authority.version}`); if (actor.subject === this.abbaIdentity || actor.provenance?.["agent_id"]) throw new Error("ABBA or an agent cannot suspend authority"); authorize(actor, SUSPEND); const suspended = structuredClone(await this.persistence.authoritySuspend({ id, expectedVersion: authority.version }) as unknown as AuthorityRecord); await this.events.append({ type: "AUTHORITY_SUSPENDED", actor: actor.subject, subject: authority.subject, outcome: "suspended", provenance: { authority_id: authority.id }, idempotency_key: `authority:suspend:${authority.id}:${authority.version}` }); return suspended; }
  async expire(id: string, now = new Date()): Promise<AuthorityRecord> { const authority = await this.require(id); if (!isExpired(authority, now)) throw new Error("Authority has not expired"); const expired = await this.markExpired(authority); await this.events.append({ type: "AUTHORITY_EXPIRED", actor: authority.subject, subject: authority.subject, outcome: "expired", provenance: { authority_id: authority.id }, idempotency_key: `authority:expire:${authority.id}:${authority.version}` }); return expired; }
  async listBySubject(subject: string): Promise<AuthorityRecord[]> { const records = await this.persistence.query("authorities", (record) => record["subject"] === subject); return records.map((record) => structuredClone(record as unknown as AuthorityRecord)); }
  private async markExpired(authority: AuthorityRecord): Promise<AuthorityRecord> { if (authority.status === "expired") return authority; return structuredClone(await this.persistence.updateIfVersion("authorities", authority.id, authority.version, { status: "expired", version: String(Number(authority.version) + 1) }) as unknown as AuthorityRecord); }
  private resourceAllowed(authority: AuthorityRecord, resourceId: string): boolean { const resources = Array.isArray(authority.constraints?.["resourceIds"]) ? authority.constraints["resourceIds"] as unknown[] : []; return resources.length === 0 || resources.includes(WILDCARD) || resources.includes(resourceId); }
  private contextAllowed(authority: AuthorityRecord, context: JsonObject): boolean { const required = authority.context ?? {}; return Object.entries(required).every(([key, value]) => context[key] === value); }
  private async require(id: string): Promise<AuthorityRecord> { const authority = await this.inspect(id); if (!authority) throw new Error(`Authority not found: ${id}`); return authority; }
}
