export type PersistenceCollection = "objects" | "relationships" | "dependencies" | "registries" | "events" | "state" | "executions" | "workflows" | "agents" | "audit" | "ledger" | "authorities";
export interface PersistenceRecord { id: string; version?: string; lifecycle?: string; authority?: unknown; provenance?: unknown; created_at?: string; updated_at?: string; [key: string]: unknown; }
export interface PersistenceTransaction { readonly id: string; commit(): Promise<void>; rollback(): Promise<void>; }
export interface AtomicRuntimeOperations { stateEvent(input: Record<string, unknown>): Promise<Record<string, unknown>>; executionAudit(input: Record<string, unknown>): Promise<Record<string, unknown>>; ledgerAudit(input: Record<string, unknown>): Promise<Record<string, unknown>>; authorityIssue(input: Record<string, unknown>): Promise<Record<string, unknown>>; authorityRevoke(input: Record<string, unknown>): Promise<Record<string, unknown>>; authoritySuspend(input: Record<string, unknown>): Promise<Record<string, unknown>>; }
export interface PersistencePort extends AtomicRuntimeOperations {
  create<T extends { id: string }>(collection: PersistenceCollection, record: T): Promise<PersistenceRecord>;
  read(collection: PersistenceCollection, id: string): Promise<PersistenceRecord | undefined>;
  update<T extends object>(collection: PersistenceCollection, id: string, patch: T): Promise<PersistenceRecord>;
  updateIfVersion<T extends object>(collection: PersistenceCollection, id: string, expectedVersion: string, patch: T): Promise<PersistenceRecord>;
  archive(collection: PersistenceCollection, id: string): Promise<PersistenceRecord>;
  query(collection: PersistenceCollection, predicate?: (record: PersistenceRecord) => boolean): Promise<PersistenceRecord[]>;
  version(collection: PersistenceCollection, id: string, version: string): Promise<PersistenceRecord>;
  transaction<T>(work: (tx: PersistencePort) => Promise<T>): Promise<T>;
}

export class MemoryPersistenceAdapter implements PersistencePort {
  private readonly stores = new Map<PersistenceCollection, Map<string, PersistenceRecord>>();
  private store(collection: PersistenceCollection): Map<string, PersistenceRecord> { let store = this.stores.get(collection); if (!store) { store = new Map<string, PersistenceRecord>(); this.stores.set(collection, store); } return store; }
  async create<T extends { id: string }>(collection: PersistenceCollection, record: T): Promise<PersistenceRecord> { const store = this.store(collection); if (store.has(record.id)) throw new Error(`Persistence record already exists: ${collection}/${record.id}`); const copy = structuredClone(record) as unknown as PersistenceRecord; store.set(record.id, copy); return structuredClone(copy); }
  async read(collection: PersistenceCollection, id: string): Promise<PersistenceRecord | undefined> { const record = this.store(collection).get(id); return record ? structuredClone(record) : undefined; }
  async update<T extends object>(collection: PersistenceCollection, id: string, patch: T): Promise<PersistenceRecord> { const store = this.store(collection); const current = store.get(id); if (!current) throw new Error(`Persistence record not found: ${collection}/${id}`); const updated: PersistenceRecord = { ...current, ...structuredClone(patch), id, updated_at: new Date().toISOString() }; store.set(id, updated); return structuredClone(updated); }
  async updateIfVersion<T extends object>(collection: PersistenceCollection, id: string, expectedVersion: string, patch: T): Promise<PersistenceRecord> { const current = await this.read(collection, id); if (!current) throw new Error(`Persistence record not found: ${collection}/${id}`); if (current.version !== expectedVersion) throw new Error(`Persistence version conflict: expected ${expectedVersion}, found ${current.version}`); return this.update(collection, id, patch); }
  async archive(collection: PersistenceCollection, id: string): Promise<PersistenceRecord> { return this.update(collection, id, { lifecycle: "archived" }); }
  async query(collection: PersistenceCollection, predicate?: (record: PersistenceRecord) => boolean): Promise<PersistenceRecord[]> { const values: PersistenceRecord[] = [...this.store(collection).values()].map((record) => structuredClone(record)); return predicate ? values.filter(predicate) : values; }
  async version(collection: PersistenceCollection, id: string, version: string): Promise<PersistenceRecord> { return this.update(collection, id, { version }); }
  async stateEvent(input: Record<string, unknown>): Promise<Record<string, unknown>> { return this.transaction(async () => { const stateId = String(input["stateId"]); const current = await this.read("state", stateId); if (!current) throw new Error(`State record not found: ${stateId}`); const expected = String(input["expectedVersion"] ?? current.version ?? "1"); const event = input["event"] as { id: string }; const eventKey = event?.["idempotency_key"]; if (eventKey) { const existing = await this.query("events", (record) => record["idempotency_key"] === eventKey); if (existing.length) return { state: current, event: existing[0], idempotent: true }; } const requested = String((input["statePatch"] as Record<string, unknown> | undefined)?.["version"] ?? ""); if (requested !== String(Number(expected) + 1)) throw new Error(`State version must advance exactly one version: expected ${expected}, requested ${requested}`); const state = await this.updateIfVersion("state", stateId, expected, (input["statePatch"] as object) ?? {}); const created = await this.create("events", event); return { state, event: created, idempotent: false }; }); }
  async executionAudit(input: Record<string, unknown>): Promise<Record<string, unknown>> { return this.transaction(async () => { const executionId = String(input["executionId"]); const current = await this.read("executions", executionId); if (!current) throw new Error(`Execution record not found: ${executionId}`); const expected = String(input["expectedVersion"] ?? current.version ?? "1"); const patch = (input["executionPatch"] as Record<string, unknown>) ?? {}; const requested = String(patch["version"] ?? ""); if (requested !== String(Number(expected) + 1)) throw new Error(`Execution version must advance exactly one version: expected ${expected}, requested ${requested}`); const execution = await this.updateIfVersion("executions", executionId, expected, patch); const audit = await this.create("audit", input["audit"] as { id: string }); return { execution, audit }; }); }
  async ledgerAudit(input: Record<string, unknown>): Promise<Record<string, unknown>> { return this.transaction(async () => { const ledger = await this.create("ledger", input["ledger"] as { id: string }); const audit = await this.create("audit", input["audit"] as { id: string }); return { ledger, audit }; }); }
  async authorityIssue(input: Record<string, unknown>): Promise<Record<string, unknown>> { return this.transaction(async () => { const key = input["idempotency_key"]; if (key) { const existing = await this.query("authorities", (record) => record["idempotency_key"] === key); if (existing.length) return existing[0]; } return this.create("authorities", input as { id: string }); }); }
  async authorityRevoke(input: Record<string, unknown>): Promise<Record<string, unknown>> { return this.updateIfVersion("authorities", String(input.id), String(input.expectedVersion), { status: "revoked", revoked_at: input.revoked_at, version: String(Number(input.expectedVersion) + 1) }); }
  async authoritySuspend(input: Record<string, unknown>): Promise<Record<string, unknown>> { return this.updateIfVersion("authorities", String(input.id), String(input.expectedVersion), { status: "suspended", version: String(Number(input.expectedVersion) + 1) }); }
  async transaction<T>(work: (tx: PersistencePort) => Promise<T>): Promise<T> { const snapshot = new Map<PersistenceCollection, Map<string, PersistenceRecord>>(); for (const [collection, records] of this.stores) snapshot.set(collection, new Map([...records].map(([id, record]) => [id, structuredClone(record)]))); try { return await work(this); } catch (error) { this.stores.clear(); for (const [collection, records] of snapshot) this.stores.set(collection, records); throw error; } }
}
