import { JsonObject, ValidationResult } from "./types";
import { MemoryPersistenceAdapter, PersistencePort, PersistenceRecord } from "./persistence";
export interface RegistryRecord { id: string; version: string; status: string; authority: JsonObject; provenance: JsonObject; metadata?: JsonObject; }
export interface RegistryAuditEntry { operation: "register" | "resolve" | "lookup" | "version" | "deprecate" | "audit"; recordId: string; occurred_at: string; actor: string; authority: JsonObject; }
const asPersistenceRecord = (value: unknown): PersistenceRecord => value as PersistenceRecord;
const canonical = <T extends RegistryRecord>(record: PersistenceRecord): T => { const copy = { ...record }; delete copy["registry_type"]; delete copy["audit_actor"]; return copy as unknown as T; };
export class Registry<T extends RegistryRecord> {
  constructor(private readonly name: string, private readonly validateRecord: (record: T) => ValidationResult, private readonly persistence: PersistencePort = new MemoryPersistenceAdapter()) {}
  async register(record: T, actor: string): Promise<T> { const validation = this.validateRecord(record); if (!validation.valid) throw new Error(`${this.name}: invalid record: ${validation.errors.join("; ")}`); const created = await this.persistence.create("registries", asPersistenceRecord({ ...record, registry_type: this.name })); await this.audit("register", record, actor); return canonical<T>(created); }
  async resolve(id: string, _actor = "runtime"): Promise<T | undefined> { const record = await this.persistence.read("registries", id); return record ? canonical<T>(record) : undefined; }
  async lookup(predicate: (record: T) => boolean, _actor = "runtime"): Promise<T[]> { const records = await this.persistence.query("registries", (record) => record["registry_type"] === this.name && predicate(canonical<T>(record))); return records.map((record) => canonical<T>(record)); }
  async version(id: string, version: string, actor: string): Promise<T> { const record = await this.resolve(id, actor); if (!record) throw new Error(`${this.name}: record not found: ${id}`); const updated = { ...record, version }; const validation = this.validateRecord(updated); if (!validation.valid) throw new Error(`${this.name}: invalid versioned record: ${validation.errors.join("; ")}`); const persisted = await this.persistence.update("registries", id, asPersistenceRecord({ ...updated, registry_type: this.name })); await this.audit("version", updated, actor); return canonical<T>(persisted); }
  async deprecate(id: string, actor: string): Promise<T> { const record = await this.resolve(id, actor); if (!record) throw new Error(`${this.name}: record not found: ${id}`); const updated = { ...record, status: "deprecated" }; const persisted = await this.persistence.update("registries", id, asPersistenceRecord({ ...updated, registry_type: this.name })); await this.audit("deprecate", updated, actor); return canonical<T>(persisted); }
  async audit(operation: RegistryAuditEntry["operation"], record: T, actor: string): Promise<void> { await this.persistence.create("audit", asPersistenceRecord({ id: `${this.name}:${operation}:${record.id}:${Date.now()}`, operation, recordId: record.id, registry_name: this.name, occurred_at: new Date().toISOString(), actor, authority: structuredClone(record.authority), provenance: structuredClone(record.provenance) })); }
  async auditLog(): Promise<RegistryAuditEntry[]> { const records = await this.persistence.query("audit", (record) => record["registry_name"] === this.name && record["recordId"] !== undefined && typeof record["operation"] === "string"); return records.map((record) => ({ operation: record["operation"] as RegistryAuditEntry["operation"], recordId: String(record["recordId"]), occurred_at: String(record["occurred_at"]), actor: String(record["actor"]), authority: structuredClone(record["authority"] as JsonObject) })); }
}
