import { SupabaseClient } from "@supabase/supabase-js";
import { PersistenceCollection, PersistencePort, PersistenceRecord } from "./persistence";
import { ProcessTask } from "./task-queue-runtime";
const TABLES: Record<PersistenceCollection, string> = { objects: "omnii_objects", relationships: "omnii_relationships", dependencies: "omnii_dependencies", registries: "omnii_registries", events: "omnii_events", state: "omnii_state", executions: "omnii_executions", workflows: "omnii_workflows", agents: "omnii_agents", audit: "omnii_audit", ledger: "omnii_ledger", authorities: "omnii_authorities", process_instances: "omnii_process_instances", process_tasks: "omnii_process_tasks" };
export class SupabasePersistenceAdapter implements PersistencePort {
  constructor(private readonly client: SupabaseClient) {}
  async create<T extends { id: string }>(collection: PersistenceCollection, record: T): Promise<PersistenceRecord> { const { data, error } = await this.client.from(TABLES[collection]).insert(record).select("*").single(); if (error) throw error; return data as PersistenceRecord; }
  async read(collection: PersistenceCollection, id: string) { const { data, error } = await this.client.from(TABLES[collection]).select("*").eq("id", id).maybeSingle(); if (error) throw error; return (data ?? undefined) as PersistenceRecord | undefined; }
  async update<T extends object>(collection: PersistenceCollection, id: string, patch: T) { const { data, error } = await this.client.from(TABLES[collection]).update({ ...patch, updated_at: new Date().toISOString() }).eq("id", id).select("*").single(); if (error) throw error; return data as PersistenceRecord; }
  async updateIfVersion<T extends object>(collection: PersistenceCollection, id: string, expectedVersion: string, patch: T) { const { data, error } = await this.client.from(TABLES[collection]).update({ ...patch, updated_at: new Date().toISOString(), version: String(Number(expectedVersion) + 1) }).eq("id", id).eq("version", expectedVersion).select("*").single(); if (error) throw error; if (!data) throw new Error(`Persistence version conflict: ${collection}/${id}`); return data as PersistenceRecord; }
  async archive(collection: PersistenceCollection, id: string) { return this.update(collection, id, { lifecycle: "archived" }); }
  async query(collection: PersistenceCollection, predicate?: (record: PersistenceRecord) => boolean): Promise<PersistenceRecord[]> { const { data, error } = await this.client.from(TABLES[collection]).select("*"); if (error) throw error; const records = (data ?? []) as PersistenceRecord[]; return predicate ? records.filter(predicate) : records; }
  async version(collection: PersistenceCollection, id: string, version: string) { return this.update(collection, id, { version }); }
  async claimProcessTask(workerId: string, leaseSeconds: number): Promise<ProcessTask | undefined> { const { data, error } = await this.client.rpc("omnii_claim_process_task", { p_worker_id: workerId, p_lease_seconds: leaseSeconds }); if (error) throw error; const result = data as { claimed?: boolean; task?: Record<string, unknown> } | null; return result?.claimed && result.task ? result.task as unknown as ProcessTask : undefined; }
  async stateEvent(input: Record<string, unknown>) { const statePatch = (input["statePatch"] ?? {}) as Record<string, unknown>; const event = input["event"] as Record<string, unknown>; const provenance = (statePatch["provenance"] ?? {}) as Record<string, unknown>; const authority = (statePatch["authority"] ?? {}) as Record<string, unknown>; const { data, error } = await this.client.rpc("omnii_atomic_state_event", { p_state_id: String(input["stateId"]), p_expected_version: String(input["expectedVersion"]), p_state_version: String(statePatch["version"]), p_state_lifecycle: String(statePatch["lifecycle"] ?? "active"), p_state_authority: authority, p_state_provenance: provenance, p_state_payload: statePatch["payload"] ?? {}, p_event_id: String(event.id), p_event_type: String(event.type), p_event_actor: String(event.actor), p_event_subject: String(event.subject ?? ""), p_event_correlation_id: String(event.correlation_id ?? ""), p_event_idempotency_key: event.idempotency_key ?? null, p_event_provenance: event.provenance ?? {}, p_event_payload: event.payload ?? {} }); if (error) throw error; return data as Record<string, unknown>; }
  async executionAudit(input: Record<string, unknown>) { const executionPatch = (input["executionPatch"] ?? {}) as Record<string, unknown>; const audit = input["audit"] as Record<string, unknown>; const { data, error } = await this.client.rpc("omnii_atomic_execution_audit", { p_execution_id: String(input["executionId"]), p_expected_version: String(input["expectedVersion"]), p_execution_version: String(executionPatch["version"] ?? "1"), p_execution_lifecycle: String(executionPatch["lifecycle"] ?? "active"), p_execution_authority: executionPatch["authority"] ?? {}, p_execution_provenance: executionPatch["provenance"] ?? {}, p_execution_payload: executionPatch, p_execution_idempotency_key: executionPatch["idempotencyKey"] ?? null, p_audit_id: String(audit.id), p_audit_authority: audit.authority ?? {}, p_audit_provenance: audit.provenance ?? {}, p_audit_payload: audit }); if (error) throw error; return data as Record<string, unknown>; }
  async ledgerAudit(input: Record<string, unknown>) { const ledger = input["ledger"] as Record<string, unknown>; const audit = input["audit"] as Record<string, unknown>; const { data, error } = await this.client.rpc("omnii_atomic_ledger_audit", { p_ledger_id: String(ledger.id), p_ledger_authority: ledger.authority ?? {}, p_ledger_provenance: ledger.provenance ?? {}, p_ledger_payload: ledger, p_ledger_idempotency_key: ledger.idempotencyKey ?? null, p_audit_id: String(audit.id), p_audit_authority: audit.authority ?? {}, p_audit_provenance: audit.provenance ?? {}, p_audit_payload: audit }); if (error) throw error; return data as Record<string, unknown>; }
  async authorityIssue(input: Record<string, unknown>) { const { data, error } = await this.client.rpc("omnii_authority_issue", { p_id: String(input.id), p_subject: String(input.subject), p_issuer: input.issuer ?? null, p_scope: input.scope ?? [], p_capabilities: input.capabilities ?? [], p_constraints: input.constraints ?? {}, p_context: input.context ?? {}, p_issued_at: input.issued_at, p_expires_at: input.expires_at ?? null, p_revocable: input.revocable ?? true, p_parent_authority_id: input.parent_authority_id ?? null, p_provenance: input.provenance ?? {}, p_idempotency_key: input.idempotency_key ?? null }); if (error) throw error; return data as Record<string, unknown>; }
  async authorityRevoke(input: Record<string, unknown>) { const { data, error } = await this.client.rpc("omnii_authority_revoke", { p_id: String(input.id), p_expected_version: String(input.expectedVersion), p_revoked_at: input.revoked_at }); if (error) throw error; return data as Record<string, unknown>; }
  async authoritySuspend(input: Record<string, unknown>) { const { data, error } = await this.client.rpc("omnii_authority_suspend", { p_id: String(input.id), p_expected_version: String(input.expectedVersion) }); if (error) throw error; return data as Record<string, unknown>; }
  async transaction<T>(_work: (tx: PersistencePort) => Promise<T>): Promise<T> { throw new Error("Durable transaction requires an explicit PostgreSQL RPC; use the named atomic operations"); }
}
export { TABLES as OMNII_PERSISTENCE_TABLES };
