import { PersistencePort } from "./persistence";
import { TransportCertificationRuntime, TransportSurfaceInput } from "./transport-certification-runtime";

export const CANONICAL_TRANSPORT_SURFACES: readonly TransportSurfaceInput[] = [
  {
    id: "charter",
    name: "CHARTER",
    role: "universal movement layer",
    architecture: "present",
    runtime: "present",
    product: "present",
    integration: "live location, mobility-provider and production dispatch adapters required",
    sourceRefs: ["docs/architecture/CHARTER_TRANSPORT_BUILD_CLOSURE.md", "packages/omnii-runtime/src/charter-runtime.ts"],
    verification: {
      status: "partial",
      methods: ["evidence-hash", "telemetry-attestation", "automated-test", "human-review"],
      standards: ["W3C VC 2.0", "W3C DID 1.1"],
      issuer: "OMNII-runtime-evidence; external operators/authorities where applicable",
      jurisdiction: "multi-jurisdiction",
      evidenceRefs: ["transport:journey", "transport:movement-event", "transport:dispatch"],
    },
    future: { maturity: "ready", humanOversight: "supervisory" },
  },
  {
    id: "nab",
    name: "NAB",
    role: "automobile biography and registry composition",
    architecture: "present",
    runtime: "present",
    product: "present",
    integration: "government registry and institutional adapters required",
    sourceRefs: ["docs/architecture/NAB_CONSTITUTION.md", "packages/omnii-runtime/src/nab-runtime.ts"],
    verification: {
      status: "partial",
      methods: ["registry-check", "digital-signature", "verifiable-credential", "decentralized-identifier", "evidence-hash", "inspection", "authority-attestation"],
      standards: ["W3C VC 2.0", "W3C DID 1.1", "ISO/IEC 18013-5"],
      issuer: "authorized registry, inspection body or other competent authority",
      jurisdiction: "NG / applicable jurisdiction",
      evidenceRefs: ["nab:birth", "nab:ownership", "nab:inspection", "nab:incident", "nab:maintenance"],
    },
    future: { maturity: "ready", cybersecurity: "required", softwareUpdateState: "tracked", humanOversight: "supervisory" },
  },
  {
    id: "fleet",
    name: "Fleet",
    role: "organizational asset operations",
    architecture: "present",
    runtime: "partial",
    product: "present",
    integration: "live telemetry, dispatch and maintenance integrations required",
    sourceRefs: ["docs/architecture/CHARTER_LOGISTICO_FLEET_BOUNDARY.md", "docs/architecture/CHARTER_LOGISTICO_FLEET_INTEGRATION_MAP.md"],
    verification: {
      status: "partial",
      methods: ["registry-check", "telemetry-attestation", "inspection", "evidence-hash", "human-review"],
      standards: ["W3C VC 2.0", "W3C DID 1.1", "UNECE R155", "UNECE R156", "ISO 24089:2023"],
      issuer: "operator, manufacturer, inspection authority or authorized service provider",
      jurisdiction: "applicable jurisdiction",
      evidenceRefs: ["fleet:assignment", "fleet:maintenance", "fleet:telemetry", "fleet:readiness"],
    },
    future: { maturity: "emerging", cybersecurity: "required", softwareUpdateState: "controlled", humanOversight: "supervisory" },
  },
  {
    id: "logistico",
    name: "Logistico",
    role: "goods and cargo movement workflow",
    architecture: "present",
    runtime: "partial",
    product: "present",
    integration: "operator, custody, customs and live cargo integrations required",
    sourceRefs: ["docs/architecture/CHARTER_LOGISTICO_FLEET_BOUNDARY.md", "UNIVERSAL_MOVEMENT.md"],
    verification: {
      status: "partial",
      methods: ["registry-check", "digital-signature", "evidence-hash", "telemetry-attestation", "human-review"],
      standards: ["W3C VC 2.0", "GS1 EPCIS-compatible event model"],
      issuer: "authorized shipper, carrier, terminal, customs or other competent participant",
      jurisdiction: "multi-jurisdiction",
      evidenceRefs: ["cargo:identity", "cargo:custody", "cargo:handoff", "cargo:delivery"],
    },
    tokenization: {
      state: "token-ready",
      instrumentType: "lawful-cargo-or-receivable-representation",
      issuer: "authorized-issuer-required",
      jurisdiction: "applicable jurisdiction",
      regulatedActivity: true,
      custody: "regulated-or-contractually-authorized-custodian-required",
      settlement: "IO-or-regulated-provider-required",
      legalEffect: "none-until-issued-and-lawfully-recognized",
      fractionalization: "lawful-when-authorized",
    },
  },
  {
    id: "hitch",
    name: "Hitch",
    role: "conditional and shared movement experience",
    architecture: "present",
    runtime: "partial",
    product: "present",
    integration: "availability, matching, identity and safety integrations required",
    sourceRefs: ["docs/architecture/CHARTER_TRANSPORT_PRODUCT_HANDOFFS.md"],
    verification: {
      status: "partial",
      methods: ["verifiable-credential", "decentralized-identifier", "human-review", "evidence-hash"],
      standards: ["W3C VC 2.0", "W3C DID 1.1"],
      issuer: "competent identity/credential issuer or verified participant",
      jurisdiction: "applicable jurisdiction",
      evidenceRefs: ["hitch:identity", "hitch:journey", "hitch:safety-report"],
    },
  },
  {
    id: "pilgrim",
    name: "Pilgrim",
    role: "pilgrimage journey composition",
    architecture: "present",
    runtime: "partial",
    product: "present",
    integration: "routes, stops, accommodation, service and safety integrations required",
    sourceRefs: ["docs/architecture/UNIVERSAL_MOVEMENT_CONSTITUTION.md"],
    verification: {
      status: "partial",
      methods: ["verifiable-credential", "digital-signature", "evidence-hash", "human-review"],
      standards: ["W3C VC 2.0", "W3C DID 1.1"],
      issuer: "service provider, institution or competent authority",
      jurisdiction: "applicable jurisdiction",
      evidenceRefs: ["pilgrim:route", "pilgrim:service", "pilgrim:completion"],
    },
  },
  {
    id: "along",
    name: "Along",
    role: "shared corridor participation",
    architecture: "present",
    runtime: "partial",
    product: "present",
    integration: "corridor, availability and live movement data required",
    sourceRefs: ["UNIVERSAL_MOVEMENT.md"],
    verification: {
      status: "partial",
      methods: ["telemetry-attestation", "evidence-hash", "human-review"],
      standards: ["W3C VC 2.0"],
      issuer: "movement operator or verified participant",
      jurisdiction: "applicable jurisdiction",
      evidenceRefs: ["along:boarding", "along:journey", "along:handoff"],
    },
  },
  {
    id: "green-mobility-energy-bridge",
    name: "Green Mobility / Energy Bridge",
    role: "energy-aware mobility connectivity",
    architecture: "present",
    runtime: "planned",
    product: "present",
    integration: "charging, CNG, fuel, station and energy-data providers required",
    sourceRefs: ["docs/architecture/CARBON_ACTUAL_ARCHITECTURE_TRACEABILITY.md", "docs/architecture/CHARTER_TRANSPORT_BUILD_CLOSURE.md"],
    verification: {
      status: "partial",
      methods: ["registry-check", "telemetry-attestation", "sensor-observation", "inspection", "evidence-hash"],
      standards: ["ISO/IEC 18013-5"],
      issuer: "station/operator/utility/inspection authority",
      jurisdiction: "applicable jurisdiction",
      evidenceRefs: ["energy:station", "energy:availability", "energy:queue", "energy:capacity"],
    },
    tokenization: {
      state: "designed",
      instrumentType: "lawful-energy-or-infrastructure-right-representation",
      issuer: "authorized-issuer-required",
      jurisdiction: "applicable jurisdiction",
      regulatedActivity: true,
      custody: "regulated-or-contractually-authorized-custodian-required",
      settlement: "IO-or-regulated-provider-required",
      legalEffect: "none-until-issued-and-lawfully-recognized",
    },
  },
  {
    id: "cngneers",
    name: "CNGNEERS",
    role: "technical engineering and mobility workforce capability",
    architecture: "present",
    runtime: "planned",
    product: "present",
    integration: "credentialing, workforce availability, booking and service-execution integrations required",
    sourceRefs: ["canon/PRODUCTS.md", "foundation-ai/pillar-ai-12.md"],
    verification: {
      status: "partial",
      methods: ["verifiable-credential", "digital-signature", "registry-check", "inspection", "human-review"],
      standards: ["W3C VC 2.0", "W3C DID 1.1"],
      issuer: "training/certification authority or authorized employer",
      jurisdiction: "applicable jurisdiction",
      evidenceRefs: ["workforce:qualification", "workforce:training", "workforce:service"],
    },
  },
  {
    id: "spare",
    name: "SPARE",
    role: "parts, repair and replacement-resource ecosystem",
    architecture: "present",
    runtime: "partial",
    product: "present",
    integration: "parts, vendor, workshop and service-network integrations required",
    sourceRefs: ["spare/product-scope.md", "spare/implementation-roadmap.md"],
    verification: {
      status: "partial",
      methods: ["registry-check", "digital-signature", "evidence-hash", "inspection", "human-review"],
      standards: ["W3C VC 2.0", "W3C DID 1.1", "GS1 EPCIS-compatible event model"],
      issuer: "manufacturer, supplier, workshop, inspector or authorized seller",
      jurisdiction: "applicable jurisdiction",
      evidenceRefs: ["part:identity", "part:compatibility", "part:service-history", "part:warranty"],
    },
  },
];

export async function registerCanonicalTransportSurfaces(
  persistence: PersistencePort,
): Promise<TransportCertificationRuntime> {
  const runtime = new TransportCertificationRuntime(persistence);
  for (const surface of CANONICAL_TRANSPORT_SURFACES) {
    if (!(await runtime.getSurface(surface.id))) {
      await runtime.registerSurface(surface);
    }
  }
  return runtime;
}
