alter table public.omnii_common_primitives
  add column if not exists denominator_scope text not null default 'ecosystem'
    check (denominator_scope in ('universal','ecosystem','domain','technology')),
  add column if not exists reuse_policy text not null default 'reuse'
    check (reuse_policy in ('reuse','extend','compose','adapter_only')),
  add column if not exists external_alignment jsonb not null default '{}'::jsonb,
  add column if not exists domain_examples jsonb not null default '[]'::jsonb;

create index if not exists omnii_common_primitives_denominator_scope_idx
  on public.omnii_common_primitives(denominator_scope, layer_role);

update public.omnii_common_primitives
set denominator_scope='ecosystem', reuse_policy='reuse', updated_at=now()
where denominator_scope is distinct from 'ecosystem';

insert into public.omnii_common_primitives
  (key, semantic_class, layer_role, canonical_backing, lifecycle, description, provenance, denominator_scope, reuse_policy, external_alignment, domain_examples)
values
('thing','THING','foundation','omnii_objects','active','A bearer of identity, description, relationships or participation; physical, digital, social, informational or abstract-as-modeled things are represented without forcing them into a domain taxonomy.','{"source":"OMNII denominator synthesis","basis":"BFO; Schema.org; RDF"}', 'universal','extend','{"bfo":"continuant/independent continuant","schema_org":"Thing","rdf":"Resource"}','["person","organization","property","document","media","machine","resource"]'::jsonb),
('agent','AGENT','foundation','identity / actor contracts','active','An entity that can bear responsibility, participate, act, delegate or be attributed within a modeled system.','{"source":"OMNII denominator synthesis","basis":"PROV; Schema.org; ORG"}', 'universal','extend','{"prov":"Agent","schema_org":"Person|Organization","org":"foaf:Agent"}','["person","organization","human_agent","ai_agent","service_agent"]'::jsonb),
('activity','ACTIVITY','foundation','IO / event / process contracts','active','A bounded occurrence in which actions, processes or interactions take place and which may consume, produce or change entities.','{"source":"OMNII denominator synthesis","basis":"PROV; Schema.org; ActivityStreams"}', 'universal','extend','{"prov":"Activity","schema_org":"Action","activitystreams":"Activity"}','["service","transaction","workflow_step","movement","interaction"]'::jsonb),
('process','PROCESS','foundation','workflow / process runtime','active','An ordered or structured temporal progression consisting of activities, states, transitions or tasks.','{"source":"OMNII denominator synthesis","basis":"BFO; PROV"}', 'universal','extend','{"bfo":"Process","prov":"Activity"}','["workflow","journey","manufacturing","service_delivery","learning"]'::jsonb),
('relation','RELATION','foundation','omnii_relationships','active','A typed connection between modeled entities, potentially temporal, directional, symmetric, hierarchical or qualified.','{"source":"OMNII denominator synthesis","basis":"RDF/RDFS; BFO; ORG"}', 'universal','extend','{"rdf":"predicate/property","rdfs":"Property","org":"relationship vocabulary"}','["ownership","membership","dependency","location","participation"]'::jsonb),
('quality','QUALITY','foundation','object attributes / measurement contracts','active','A dependent characteristic or measurable attribute of an entity or process that may vary by time or context.','{"source":"OMNII denominator synthesis","basis":"BFO; SSN/SOSA"}', 'universal','extend','{"bfo":"Quality","ssn_sosa":"ObservableProperty"}','["condition","capacity","temperature","reputation","quality_score"]'::jsonb),
('state','STATE','foundation','ACTUAL / lifecycle contracts','active','A temporally situated configuration or condition of an entity, relationship or process.','{"source":"OMNII denominator synthesis","basis":"BFO change literature; ActivityStreams; OMNII lifecycle"}', 'universal','extend','{"activitystreams":"stateful object properties","omnii":"lifecycle/state"}','["active","pending","completed","verified","disputed"]'::jsonb),
('change','CHANGE','foundation','IO / state transition contracts','active','A modeled difference or transition between states, values, relationships or configurations.','{"source":"OMNII denominator synthesis","basis":"BFO change research; PROV derivation"}', 'universal','extend','{"bfo":"explicit change modeling research","prov":"Derivation/Generation/Invalidation"}','["creation","update","transfer","movement","revocation"]'::jsonb),
('identity','IDENTITY','foundation','omnii_objects / ROOT / HAPI','active','Persistent reference to the same modeled entity across representations and systems, subject to verification and provenance.','{"source":"OMNII existing canonical","basis":"Schema.org identifier; PROV attribution; RDF resources"}', 'universal','reuse','{"schema_org":"identifier","rdf":"IRI/resource identity","prov":"Agent/Entity"}','["person","organization","device","account","document"]'::jsonb),
('identifier','IDENTIFIER','common','namespaces / object identifiers','active','A value or URI-like reference used to distinguish or resolve a modeled entity or record.','{"source":"OMNII denominator synthesis","basis":"Schema.org; ORG; RDF; ISO/IEC 11179"}', 'universal','reuse','{"schema_org":"identifier","org":"identifier","rdf":"IRI","iso_11179":"data element identity"}','["national_id","registry_id","uri","uuid","external_id"]'::jsonb),
('information','INFORMATION','foundation','documents / knowledge / representations','active','Represented content, data or information artifact that can describe, encode, communicate or be processed.','{"source":"OMNII denominator synthesis","basis":"RDF; Schema.org CreativeWork; metadata registry practice"}', 'universal','extend','{"rdf":"graph/literal","schema_org":"CreativeWork","iso_11179":"data representation/meaning"}','["data","document","record","message","model"]'::jsonb),
('collection','COLLECTION','common','registry / collection / grouping contracts','active','A bounded grouping or aggregation of entities, records, activities or other members with membership semantics.','{"source":"OMNII denominator synthesis","basis":"PROV Collection; RDF datasets; ActivityStreams Collection"}', 'universal','reuse','{"prov":"Collection","rdf":"Dataset/Graph","activitystreams":"Collection"}','["registry","portfolio","playlist","case_file","organization_unit"]'::jsonb),
('measurement','MEASUREMENT','cross_cutting','units / observations / analytics','active','An observation or computed representation of a quantity or characteristic using a unit, scale, procedure or method where applicable.','{"source":"OMNII denominator synthesis","basis":"SSN/SOSA; ISO/IEC 11179"}', 'universal','extend','{"ssn_sosa":"Observation","iso_11179":"units/value domains/derivation"}','["price","weight","distance","quality","performance"]'::jsonb),
('time','TIME','foundation','location_time / temporal contracts','active','Temporal position, interval, duration, ordering and validity context.','{"source":"OMNII denominator synthesis","basis":"W3C OWL-Time"}', 'universal','reuse','{"owl_time":"Instant|Interval|Duration|TemporalEntity"}','["timestamp","deadline","schedule","validity","history"]'::jsonb),
('place','PLACE','foundation','location / operating-context contracts','active','Spatial or locational context in which entities, activities or relationships are situated.','{"source":"OMNII denominator synthesis","basis":"Schema.org Place; OWL-Time spatial usage; SSN context"}', 'universal','reuse','{"schema_org":"Place","ssn_sosa":"FeatureOfInterest context"}','["address","territory","facility","route","jurisdiction"]'::jsonb),
('representation','REPRESENTATION','common','object/token/document projection contracts','active','A representation of another entity, right, state or information artifact; representation must not silently become the represented authority or truth.','{"source":"OMNII existing canonical","basis":"Schema.org Thing/CreativeWork; OMNII tokenization doctrine"}', 'universal','reuse','{"schema_org":"Thing/CreativeWork","omnii":"representation/tokenization boundary"}','["token","document","profile","public_view","api_payload"]'::jsonb),
('context','CONTEXT','common','operating contexts','active','The scoped circumstances used to interpret an entity, action, decision or relationship, including time, place, identity, jurisdiction and policy.','{"source":"OMNII existing canonical","basis":"cross-standard synthesis"}', 'universal','reuse','{"omnii":"operating context","prov":"activity/entity context","owl_time":"temporal context"}','["jurisdiction","session","case","territory","organization_context"]'::jsonb),
('purpose','PURPOSE','common','intent / mission / scope contracts','active','The reason, objective, mission or intended end associated with an entity, activity, organization or policy.','{"source":"OMNII denominator synthesis","basis":"ORG purpose; Schema.org Action/HowTo patterns"}', 'universal','extend','{"org":"purpose","schema_org":"Action/CreativeWork purpose-related modeling"}','["goal","mission","request","program","policy"]'::jsonb),
('intent','INTENT','foundation','omnii_objects / workflow contracts','active','A represented desired direction, need, request, offer, commitment or sought outcome before execution.','{"source":"OMNII existing canonical"}', 'ecosystem','reuse','{"omnii":"Intent"}','["trade","service","education","governance","transport"]'::jsonb),
('capability','CAPABILITY','foundation','capability registries / omnii_objects','active','An ability, capacity or functional potential that may be subject to explicit authority and constraints.','{"source":"OMNII existing canonical","basis":"BFO realizables; capability-centric ecosystem design"}', 'ecosystem','reuse','{"bfo":"Disposition/Function/Realizable","omnii":"Capability"}','["human","ai","service","machine","organization"]'::jsonb),
('authority','AUTHORITY','cross_cutting','omnii_authorities / SEAL','active','Issued and scoped power or mandate to act, decide, represent or confer permissions.','{"source":"OMNII existing canonical","basis":"PROV responsibility; ODRL parties/rules; OMNII authority doctrine"}', 'ecosystem','reuse','{"prov":"Agent responsibility/delegation","odrl":"Party/Policy/Permission"}','["human","institution","government","delegation","mandate"]'::jsonb),
('authorization','AUTHORIZATION','cross_cutting','ABBA execution guards / policy contracts','active','A decision that a proposed action is permitted under applicable authority, policy and context; it is not identity itself.','{"source":"OMNII existing canonical","basis":"ODRL Permission/Prohibition/Duty"}', 'ecosystem','reuse','{"odrl":"Permission/Prohibition/Duty/Constraint"}','["execution","payment","publication","access","approval"]'::jsonb),
('obligation','OBLIGATION','common','economic / policy / workflow contracts','active','A required duty, commitment or condition attached to a party, action, resource, right or agreement.','{"source":"OMNII denominator synthesis","basis":"ODRL Duty/Obligation"}', 'ecosystem','reuse','{"odrl":"Duty/obligation"}','["contract","loan","service","compliance","employment"]'::jsonb),
('evidence','EVIDENCE','common','evidence_objects / proof_records','active','Information or observation supporting a claim, decision, state or outcome, with provenance and confidence where applicable.','{"source":"OMNII existing canonical","basis":"PROV; SSN/SOSA"}', 'ecosystem','reuse','{"prov":"Entity/Activity provenance","ssn_sosa":"Observation"}','["document","photo","measurement","attestation","audit"]'::jsonb),
('provenance','PROVENANCE','cross_cutting','audit / provenance contracts','active','Information about origins, transformations, responsibility, timing and derivation of entities or activities.','{"source":"W3C PROV","basis":"PROV-DM"}', 'ecosystem','reuse','{"prov":"Entity|Activity|Agent; derivation; attribution; delegation"}','["data_lineage","decision","media","registry","ai_output"]'::jsonb),
('policy','POLICY','cross_cutting','control / compliance / governance contracts','active','A structured set of rules governing permissions, prohibitions, duties, constraints or required behavior.','{"source":"ODRL; OMNII governance"}', 'ecosystem','reuse','{"odrl":"Policy/Rule/Permission/Prohibition/Duty/Constraint"}','["access","privacy","trade","governance","licensing"]'::jsonb),
('decision','DECISION','common','approval / adjudication / governance contracts','active','A consequential determination selecting, approving, rejecting, ranking or directing a course under evidence, authority and policy.','{"source":"OMNII denominator synthesis","basis":"ODRL policy evaluation; workflow/governance patterns"}', 'ecosystem','reuse','{"odrl":"policy evaluation semantics","omnii":"approval/adjudication"}','["award","license","promotion","procurement","dispute"]'::jsonb),
('service','SERVICE','common','General Service','active','A capability made available to fulfill an intent, request or outcome under agreed conditions.','{"source":"OMNII existing canonical"}', 'ecosystem','reuse','{"schema_org":"Service/Action patterns","omnii":"General Service"}','["transport","education","health","government","commerce"]'::jsonb),
('request','REQUEST','common','forms / workflow contracts','active','A directed demand for information, action, service, resource, decision or other outcome.','{"source":"OMNII denominator synthesis","basis":"service/workflow/common interaction standards"}', 'ecosystem','reuse','{"omnii":"request/application/submission"}','["service","support","permit","payment","information"]'::jsonb),
('workflow','WORKFLOW','common','institutional workflows / process runtime','active','Reusable orchestration of states, tasks, approvals, exceptions and outcomes.','{"source":"OMNII existing canonical"}', 'ecosystem','reuse','{"omnii":"process/workflow runtime"}','["admission","procurement","compliance","claims","service"]'::jsonb),
('interaction','INTERACTION','common','IO / event contracts','active','A meaningful exchange or occurrence involving participants, inputs, outputs, handoffs or state effects.','{"source":"OMNII existing canonical","basis":"ActivityStreams; PROV Activity"}', 'ecosystem','reuse','{"activitystreams":"Activity","prov":"Activity"}','["message","trade","handoff","transaction","movement"]'::jsonb),
('audit','AUDIT','cross_cutting','omnii_audit / audit contracts','active','Structured review of evidence, controls, actions or state for accountability, assurance or improvement.','{"source":"OMNII existing canonical"}', 'ecosystem','reuse','{"prov":"provenance/accountability","omnii":"audit"}','["financial","security","compliance","quality","governance"]'::jsonb),
('registry','REGISTRY','common','omnii_registries / canonical registries','active','Governed catalog of entities, metadata, identifiers, relationships or controlled reference information, distinct from the operational records it describes.','{"source":"OMNII existing canonical","basis":"ISO/IEC 11179 metadata registry"}', 'ecosystem','reuse','{"iso_11179":"metadata registry"}','["population","vehicle","property","institution","credential"]'::jsonb),
('value','VALUE','foundation','economic vectors / compositions / valuation','active','Universal representation of monetary and non-monetary value, including cost, benefit, capacity and obligation.','{"source":"OMNII existing canonical"}', 'ecosystem','reuse','{"omnii":"Value/Economic model"}','["money","time","capacity","attention","rights"]'::jsonb),
('interoperability','INTEROPERABILITY','integration','API / connector / protocol adapters','active','Stable mechanisms for connecting the common model to external systems, protocols, schemas and providers without making any provider constitutional.','{"source":"OMNII existing canonical","basis":"RDF; OpenAPI; ISO/IEC 11179"}', 'ecosystem','adapter_only','{"rdf":"linked data interoperability","openapi":"components/security","iso_11179":"shared metadata meanings"}','["api","webhook","mcp","a2a","import_export"]'::jsonb)
on conflict (key) do update set
  semantic_class=excluded.semantic_class,
  layer_role=excluded.layer_role,
  canonical_backing=excluded.canonical_backing,
  lifecycle=excluded.lifecycle,
  description=excluded.description,
  provenance=excluded.provenance,
  denominator_scope=excluded.denominator_scope,
  reuse_policy=excluded.reuse_policy,
  external_alignment=excluded.external_alignment,
  domain_examples=excluded.domain_examples,
  updated_at=now();

comment on column public.omnii_common_primitives.denominator_scope is 'Classification of reusable denominator scope: universal cross-domain abstraction, Carbon Actual ecosystem capability, domain capability, or technology implementation.';
comment on column public.omnii_common_primitives.external_alignment is 'Non-binding alignment references to external standards/ontologies. External standards do not become constitutional authority.';
comment on column public.omnii_common_primitives.reuse_policy is 'Whether downstream implementations should reuse, extend, compose, or adapter-only consume the denominator.';
