-- OMNII ecosystem capability shelf, completeness contract, and open-world scenario grammar.
-- Reuses the canonical runtime substrate: registries, workflows, objects, and ledger.

insert into public.omnii_registries
  (id, version, lifecycle, authority, provenance, payload, correlation_id, created_at, updated_at)
values
  ('capability:analysis','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"analysis","name":"Data analysis","kind":"analysis","outputs":["analysis-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:research','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"research","name":"Research","kind":"research","outputs":["research-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:documentation','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"documentation","name":"Documentation","kind":"documentation","outputs":["documentation-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:modeling','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"modeling","name":"Modeling","kind":"modeling","outputs":["modeling-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:design','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"design","name":"Design","kind":"design","outputs":["design-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:planning','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"planning","name":"Planning","kind":"planning","outputs":["planning-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:consulting','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"consulting","name":"Consulting","kind":"consulting","outputs":["consulting-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:audit','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"audit","name":"Audit","kind":"audit","outputs":["audit-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:assessment','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"assessment","name":"Assessment","kind":"assessment","outputs":["assessment-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:forecasting','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"forecasting","name":"Forecasting","kind":"forecasting","outputs":["forecasting-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:feasibility','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"feasibility","name":"Feasibility study","kind":"feasibility","outputs":["feasibility-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:strategy','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"strategy","name":"Strategy","kind":"strategy","outputs":["strategy-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:standardization','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"standardization","name":"Standardization","kind":"standardization","outputs":["standardization-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:certification','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"certification","name":"Certification","kind":"certification","outputs":["certification-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:compliance','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"compliance","name":"Compliance","kind":"compliance","outputs":["compliance-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:verification','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"verification","name":"Verification","kind":"verification","outputs":["verification-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:workflow','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"workflow","name":"Workflow","kind":"workflow","outputs":["workflow-output"]}'::jsonb,'ecosystem-capability-seed',now(),now()),
  ('capability:delivery','1','active','{}'::jsonb,'{"source":"OMNII constitutional capability shelf"}'::jsonb,'{"id":"delivery","name":"Delivery","kind":"delivery","outputs":["delivery-output"]}'::jsonb,'ecosystem-capability-seed',now(),now())
on conflict (id) do update set version=excluded.version,lifecycle=excluded.lifecycle,provenance=excluded.provenance,payload=excluded.payload,updated_at=now();

insert into public.omnii_registries
  (id, version, lifecycle, authority, provenance, payload, correlation_id, created_at, updated_at)
values
  ('artifact:catalog','1','active','{}'::jsonb,'{"source":"OMNII constitutional artifact catalog"}'::jsonb,'{"types":["report","data-analysis","dashboard","document","slide-deck","proposal","policy","sop","business-case","feasibility-study","swot-analysis","risk-assessment","financial-model","implementation-plan","standard","specification","audit-report","assessment","certificate","compliance-pack","contract","decision-record"]}'::jsonb,'ecosystem-artifact-catalog',now(),now()),
  ('constitutional:completeness-contract','1','active','{}'::jsonb,'{"source":"OMNII Ecosystem Capability & Completeness Contract"}'::jsonb,'{"principle":"Nothing leaves the ecosystem as complete merely because an artifact was generated.","required":["capabilities","artifacts","evidence","standards","dependencies","outcome","reconciliation"],"openWorld":true}'::jsonb,'ecosystem-completeness-contract',now(),now()),
  ('constitutional:scenario-grammar','1','active','{}'::jsonb,'{"source":"OMNII open-world scenario grammar"}'::jsonb,'{"primitives":["entity","identity","state","relationship","intent","need","capability","resource","constraint","condition","context","location","time","event","action","cause","effect","reason","decision","outcome","evidence","claim","authority","exception","recovery","continuity","counterfactual","uncertainty","observation"],"relations":["causes","contributes_to","correlates_with","prevents","enables","requires","depends_on","results_in","intended_to","suspected_cause","disputed_cause","reverses","supersedes","branches_to","merges_with","follows","interrupts","recovers","observed_as","supported_by","contradicted_by"],"patterns":["linear_chain","branching_chain","merge","feedback_loop","escalation","prevention","failure_recovery","reversal","dependency_chain","counterfactual","uncertain_causality","real_digital_bridge"],"openWorld":true}'::jsonb,'ecosystem-scenario-grammar',now(),now()),
  ('constitutional:real-digital-boundary','1','active','{}'::jsonb,'{"source":"OMNII real/digital continuity contract"}'::jsonb,'{"principles":["physical_entity_is_not_its_digital_representation","observation_is_not_fact","claim_is_not_evidence","digital_action_must_record_real_world_effect_when_applicable","real_world_change_must_be_representable_digitally_when_observed"],"unknownsAllowed":true,"provenanceRequired":true}'::jsonb,'ecosystem-real-digital-boundary',now(),now()),
  ('constitutional:no-loss-contract','1','active','{}'::jsonb,'{"source":"OMNII no-loss continuity doctrine"}'::jsonb,'{"materiality":["money","assets","people","time","energy","knowledge","evidence","authority","relationships","state"],"requiredTransitions":["before","action","after"],"failureStatesAllowed":true,"recoveryRequired":true,"historyPreserved":true,"silentDeletion":false}'::jsonb,'ecosystem-no-loss-contract',now(),now())
on conflict (id) do update set version=excluded.version,lifecycle=excluded.lifecycle,provenance=excluded.provenance,payload=excluded.payload,updated_at=now();

create index if not exists idx_omnii_registries_payload_id on public.omnii_registries using gin (payload);
create index if not exists idx_omnii_objects_payload on public.omnii_objects using gin (payload);
create index if not exists idx_omnii_ledger_payload on public.omnii_ledger using gin (payload);
