drop policy if exists omnii_causal_authenticated on public.omnii_causal_relations;
drop policy if exists omnii_gaps_authenticated on public.omnii_completeness_gaps;
drop policy if exists "authenticated access economic allocations" on public.omnii_economic_allocations;
drop policy if exists economic_compositions_authenticated on public.omnii_economic_compositions;
drop policy if exists "authenticated access economic entitlements" on public.omnii_economic_entitlements;
drop policy if exists "authenticated access economic events" on public.omnii_economic_events;
drop policy if exists economic_vectors_authenticated on public.omnii_economic_vectors;
drop policy if exists "authenticated access ecosystem benchmarks" on public.omnii_ecosystem_benchmarks;
drop policy if exists omnii_interparticipant_protocols_authenticated on public.omnii_interparticipant_protocols;
drop policy if exists omnii_knowledge_authenticated on public.omnii_knowledge_assertions;
drop policy if exists omnii_name_resolutions_authenticated on public.omnii_name_resolutions;
drop policy if exists omnii_namespaces_authenticated on public.omnii_namespaces;
drop policy if exists omnii_participants_authenticated on public.omnii_participants;
drop policy if exists omnii_quality_authenticated on public.omnii_quality_assessments;
drop policy if exists omnii_reconciliation_authenticated on public.omnii_reconciliations;
drop policy if exists omnii_scenario_edges_authenticated on public.omnii_scenario_edges;
drop policy if exists omnii_scenario_nodes_authenticated on public.omnii_scenario_nodes;
drop policy if exists "authenticated access settlements" on public.omnii_settlements;
drop policy if exists "authenticated access valuation methods" on public.omnii_valuation_methods;
create policy omnii_causal_authenticated_read on public.omnii_causal_relations for select to authenticated using (true);
create policy omnii_interparticipant_protocols_authenticated_read on public.omnii_interparticipant_protocols for select to authenticated using (true);
create policy omnii_knowledge_authenticated_read on public.omnii_knowledge_assertions for select to authenticated using (true);
create policy omnii_name_resolutions_authenticated_read on public.omnii_name_resolutions for select to authenticated using (true);
create policy omnii_namespaces_authenticated_read on public.omnii_namespaces for select to authenticated using (true);
create policy omnii_participants_authenticated_read on public.omnii_participants for select to authenticated using (true);
create policy omnii_scenario_edges_authenticated_read on public.omnii_scenario_edges for select to authenticated using (true);
create policy omnii_scenario_nodes_authenticated_read on public.omnii_scenario_nodes for select to authenticated using (true);
revoke insert, update, delete, truncate, references, trigger on table public.omnii_causal_relations, public.omnii_completeness_gaps, public.omnii_economic_allocations, public.omnii_economic_compositions, public.omnii_economic_entitlements, public.omnii_economic_events, public.omnii_economic_vectors, public.omnii_ecosystem_benchmarks, public.omnii_interparticipant_protocols, public.omnii_knowledge_assertions, public.omnii_name_resolutions, public.omnii_namespaces, public.omnii_participants, public.omnii_quality_assessments, public.omnii_reconciliations, public.omnii_scenario_edges, public.omnii_scenario_nodes, public.omnii_settlements, public.omnii_valuation_methods from anon, authenticated;
revoke select on table public.omnii_completeness_gaps, public.omnii_economic_allocations, public.omnii_economic_compositions, public.omnii_economic_entitlements, public.omnii_economic_events, public.omnii_economic_vectors, public.omnii_ecosystem_benchmarks, public.omnii_quality_assessments, public.omnii_reconciliations, public.omnii_settlements, public.omnii_valuation_methods from anon, authenticated;
revoke all on table public.omnii_completeness_gaps, public.omnii_economic_allocations, public.omnii_economic_compositions, public.omnii_economic_entitlements, public.omnii_economic_events, public.omnii_economic_vectors, public.omnii_ecosystem_benchmarks, public.omnii_quality_assessments, public.omnii_reconciliations, public.omnii_settlements, public.omnii_valuation_methods from public;
revoke all on table public.omnii_causal_relations, public.omnii_interparticipant_protocols, public.omnii_knowledge_assertions, public.omnii_name_resolutions, public.omnii_namespaces, public.omnii_participants, public.omnii_scenario_edges, public.omnii_scenario_nodes from public;
