revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_agent_runs from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_agents from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_authorities from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_control_findings from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_cve_findings from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_cve_rules from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_cve_runs from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_execution_controls from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_executions from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_ledger from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_process_instances from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_process_tasks from anon, authenticated;
revoke select, insert, update, delete, truncate, references, trigger on table public.omnii_state from anon, authenticated;
revoke all on table public.omnii_agent_runs from public;
revoke all on table public.omnii_agents from public;
revoke all on table public.omnii_authorities from public;
revoke all on table public.omnii_control_findings from public;
revoke all on table public.omnii_cve_findings from public;
revoke all on table public.omnii_cve_rules from public;
revoke all on table public.omnii_cve_runs from public;
revoke all on table public.omnii_execution_controls from public;
revoke all on table public.omnii_executions from public;
revoke all on table public.omnii_ledger from public;
revoke all on table public.omnii_process_instances from public;
revoke all on table public.omnii_process_tasks from public;
revoke all on table public.omnii_state from public;
