import type { IdentityRef, NameRef, CorrelationEvidence } from "../identity";
import type { ResolutionResult } from "../resolution";
export type ResolverReference=IdentityRef|NameRef;
export interface ResolverAdapter{readonly adapterId:string;readonly schemes:readonly string[];supports(reference:ResolverReference):boolean;resolve(reference:ResolverReference):Promise<ResolutionResult>;}
export interface DidMethodDriver{readonly method:string;resolve(reference:IdentityRef):Promise<{records:Readonly<Record<string,unknown>>;evidence:readonly CorrelationEvidence[];verified?:boolean}>;}
export class DidResolverAdapter implements ResolverAdapter{readonly schemes=["did"] as const;private readonly drivers:ReadonlyMap<string,DidMethodDriver>;constructor(readonly adapterId:string,drivers:readonly DidMethodDriver[]){this.drivers=new Map(drivers.map(d=>[d.method,d]));}supports(r:ResolverReference){return r.scheme==="did";}async resolve(r:ResolverReference):Promise<ResolutionResult>{if(r.scheme!=="did")throw new Error("DID adapter received non-DID reference");if(!('value' in r))throw new Error("DID resolver requires an identity reference");const method=r.method??r.value.split(":")[1];const driver=this.drivers.get(method);if(!driver)return{reference:r,adapterId:this.adapterId,status:"unresolved",records:{},evidence:[]};const result=await driver.resolve(r);return{reference:r,adapterId:this.adapterId,status:"resolved",...result};}}
interface RecordResolver{(reference:ResolverReference):Promise<{records:Readonly<Record<string,unknown>>;evidence:readonly CorrelationEvidence[];verified?:boolean;metadata?:Readonly<Record<string,unknown>>}>;}
class FunctionResolverAdapter implements ResolverAdapter{constructor(readonly adapterId:string,readonly schemes:readonly string[],private readonly resolver:RecordResolver){}supports(r:ResolverReference){return this.schemes.includes(r.scheme);}async resolve(r:ResolverReference):Promise<ResolutionResult>{if(!this.supports(r))throw new Error(`unsupported scheme: ${r.scheme}`);try{return{reference:r,adapterId:this.adapterId,status:"resolved",...(await this.resolver(r))};}catch(error){return{reference:r,adapterId:this.adapterId,status:"error",records:{},evidence:[],metadata:{error:error instanceof Error?error.message:String(error)}};}}}
export class EnsResolverAdapter extends FunctionResolverAdapter{constructor(id:string,resolver:RecordResolver){super(id,["ens"],resolver);}}
export class HnsResolverAdapter extends FunctionResolverAdapter{constructor(id:string,resolver:RecordResolver){super(id,["hns"],resolver);}}
export class DnsResolverAdapter extends FunctionResolverAdapter{constructor(id:string,resolver:RecordResolver){super(id,["dns"],resolver);}}
export function selectResolverAdapter(reference:ResolverReference,adapters:readonly ResolverAdapter[]):ResolverAdapter|undefined{return adapters.find(adapter=>adapter.supports(reference));}
